# -*- coding: utf-8 -*-
"""project2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SFDd_wv8Sjj8tzv3RdGLdFbO-s4d97lH
"""

!pip install deepface

from deepface import DeepFace

import cv2
import matplotlib.pyplot as plt

img = cv2.imread('/content/mukki.jpg')
plt.imshow(img)

plt.imshow(cv2.cvtColor(img,cv2.COLOR_BGR2RGB))

prediction = DeepFace.analyze(img)

prediction

type(prediction)

prediction['dominant_emotion']

faceCascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
     # print(faceCascade.empty())
faces = faceCascade.detectMultiScale(gray,1.1,4)
    # Draw a rectangle around the faces
for(x, y, w, h) in faces:
  cv2.rectangle(img, (x, y), (x+w, y+h), (0, 255, 0), 2)

plt.imshow(cv2.cvtColor(img,cv2.COLOR_BGR2RGB))

font = cv2.FONT_HERSHEY_SIMPLEX
cv2.putText(img,
            prediction['dominant_emotion'],
            (0, 50),
            font, 1,
            (0, 0, 255),
            2,
            cv2.LINE_4);

plt.imshow(cv2.cvtColor(img,cv2.COLOR_BGR2RGB))

