# -*- coding: utf-8 -*-
"""project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F44_iF_RcTxP3i8EyOni1iMeMxDjj88Z
"""

!pip install deepface

from deepface import DeepFace

import cv2
import matplotlib.pyplot as plt

img = cv2.imread('/content/happy_boy.jpg')
plt.imshow(img)

!pip install tensorflow

!pip install -r install_deepface.txt

!pip install flask

!pip install pillow

result = DeepFace.analyze(img, actions=['emotion'])

print(result)

img1 = cv2.imread('/content/sadboy.jpg')
plt.imshow(img1)

plt.imshow(cv2.cvtColor(img1,cv2.COLOR_BGR2RGB))

result1 = DeepFace.analyze(img1, actions=['emotion'])

print(result1)

"""# New Section

# New Section
"""

import numpy

img2 = cv2.imread('/content/surprisedboy.jpg')
plt.imshow(img2)



plt.imshow(cv2.cvtColor(img2,cv2.COLOR_BGR2RGB))

img3 = cv2.imread('/content/angryboy.jpg')
plt.imshow(img3)

plt.imshow(cv2.cvtColor(img3,cv2.COLOR_BGR2RGB))

result2 = DeepFace.analyze(img3, actions=['emotion'])

print(result2)

result2 = DeepFace.analyze(img3)

result2

type(result2)

result2['dominant_emotion']

# we are trying to drawa a rectangle across the face

faceCascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

gray = cv2.cvtColor(img3, cv2.COLOR_BGR2GRAY)
     # print(faceCascade.empty())
faces = faceCascade.detectMultiScale(gray,1.1,4)
    # Draw a rectangle around the faces
for(x, y, w, h) in faces:
  cv2.rectangle(img3, (x, y), (x+w, y+h), (0, 255, 0), 2)

plt.imshow(cv2.cvtColor(img3,cv2.COLOR_BGR2RGB))

font = cv2.FONT_HERSHEY_SIMPLEX
cv2.putText(img3,
            result2['dominant_emotion'],
            (0, 50),
            font, 1,
            (0, 0, 255),
            2,
            cv2.LINE_4);

plt.imshow(cv2.cvtColor(img3,cv2.COLOR_BGR2RGB))

